### ISSUE TITLE
chatgpt4无法处理网址，报“浏览出错”

### ISSUE THREAD

**Issue by SilenceHell** [FakeOpenAI/FakeOpenAI#7]
如题

![微信截图_202](https://github.com/FakeOpenAI/FakeOpenAI/assets/20390652/29d0f2ab-91c2-40b0-8f65-4fbca80bc7a8)

**Comment by CaoBaoQi** [comment]
![QQ20240204-201810](https://github.com/FakeOpenAI/FakeOpenAI/assets/150160572/f327a043-da13-4746-aabf-9fabe9d71382)
show

**Comment by CaoBaoQi** [comment]
@SilenceHell 在 插件中启用 LinkReader 可以实现访问 Link

**Comment by SilenceHell** [comment]
> ![QQ20240204-201810](https://private-user-images.githubusercontent.com/150160572/302102061-f327a043-da13-4746-aabf-9fabe9d71382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNDk3MDcsIm5iZiI6MTcwNzA0OTQwNywicGF0aCI6Ii8xNTAxNjA1NzIvMzAyMTAyMDYxLWYzMjdhMDQzLWRhMTMtNDc0Ni1hYWJmLTlmYWJlOWQ3MTM4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxMjIzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTE1MTk4NTYyMjZkMzFmYTRiNjkwNWUzNDM3MzM0OGM3MTU1NzQ1ODRlMDg3N2FlMDA0MjNmZTQ0Y2U3MmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fIDvFG7jEqyUHCVdHYytS347whfGVAhWESoZIEDqFV4) show

哈哈哈，第一次吃榴莲，不知道要剥壳，你看我这没见识的样子~

**Comment by SilenceHell** [comment]
> 别说你了，我自己都不知道咋回事，但是我知道这不是网站问题哈哈哈，我也很少用gpt的插件

感谢！
